---

# This is temperary solution to get bits from SMP

# Due to the file permission limitation with blob (always 770), we currently only support using azure files.
- name: Install unzip
  package: 
    name: unzip
    state: present

# Explicitly install bs4 with python3
- name: Install beautifulsoup4
  command: |
    pip3 install beautifulsoup4
  become: true

- name: Check whether the installation media already exists and has been extracted
  stat: path={{ hana_software_loc }}
  register: extract_path_status

- name: Ensure installation media is downloaded and extracted
  when: extract_path_status.stat.exists == false
  block: 

    - name: Download installation media
      shell: "python3 /var/lib/waagent/custom-script/download/0/sapansible/python/downloader/basket.py --config /var/lib/waagent/custom-script/download/0/sapansible/ansible/output.json --dir {{ azure_files_mount_path }}"
