---

nfs_exports:
- path: "{{ target_media_location }}"
  export_settings: "*(rw,no_root_squash,sync,no_subtree_check)"
- path: "/usr/sap/{{ app_sid | upper }}/SYS"
  export_settings: "*(rw,no_root_squash,sync,no_subtree_check)"
- path: "/tmp/app_template"
  export_settings: "*(rw,no_root_squash,sync,no_subtree_check)"
- path: "/sapmnt/{{ app_sid | upper}}/global"
  export_settings: "*(rw,no_root_squash,sync,no_subtree_check)"
- path: "/sapmnt/{{ app_sid | upper}}/profile"
  export_settings: "*(rw,no_root_squash,sync,no_subtree_check)"
