#!/usr/bin/env python3
# 
#       SMP Downloader
#
#       License:        GNU General Public License (GPL)
#       (c) 2019        Microsoft Corp.
#

class Package(object):
    selector_newest = 'max(range(len(results)), key=lambda index: results[index]["ReleaseDate"])'
    selector_oldest = 'min(range(len(results)), key=lambda index: results[index]["ReleaseDate"])'
    dir_db          = "DB"
    dir_app         = "APP"
    dir_rti         = "RTI"
    os_linux        = "LINUX_X64"
    os_windows      = "NT_X64"
    os_indep        = "OSINDEP"
    
    def __init__(self, name=None, target_dir=None, retr_params=None, condition=None, filter=None, os_avail=None, os_var=None, selector=None):
        self.name        = name if name else ""
        self.target_dir  = target_dir if target_dir else ""
        self.retr_params = retr_params if retr_params else ""
        self.condition   = condition if condition else []
        self.filter      = filter if filter else []
        self.os_avail    = os_avail if os_avail else []
        self.os_var      = os_var if os_var else ""
        self.selector    = selector if selector else ""

class Scenario(object):
    def __init__(self, name=None, required_params=None, packages=None):
        self.name            = name
        self.required_params = required_params if required_params else []
        self.packages        = packages if packages else []

class DBScenario(Scenario):
    def __init__(self, **kwargs):
        super(DBComponent, self).__init__(**kwargs)

S4 = Scenario(
    required_params = [],
    packages = [
        Package(
            name        = "SWPM20",
            target_dir  = Package.dir_rti,
            retr_params = {"ENR": "73555000100200007684"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "EA-HR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "67838200100200018971"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "GBX01HR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200000236"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "GBX01HR5",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200000237"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "igsexe",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100059519"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "igshelper",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100059519"},
            filter      = None,
            os_avail    = [Package.os_indep],
            os_var      = 'Package.os_indep',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-10001",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000101100023153"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-10002",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100033768"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-10003",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100038098"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-10004",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100038564"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-10005",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100042192"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-10006",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000101100034903"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-10007",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000101100038272"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-10008",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100049559"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-10009",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000101100040875"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-10010",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100056598"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-100AGINUIHR002",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200006076"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-20001",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000101100017868"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-20002",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100023444"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-20003",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000101100021684"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-20004",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100029926"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-20005",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000101100024195"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-20006",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100033861"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-20007",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100038131"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-20008",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100042191"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-200AGINUIMDG001",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200002606"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-30001",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100042144"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-30002",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000101100034873"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-30003",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100049621"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-30004",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000101100040860"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-300AGINUITRV001",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200008904"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-600AGINUIBAS",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011041"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-600AGINUIS4H",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011363"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-74014INSTPI",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900101100057586"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-75501INSAPUI",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000101100048069"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "K-800AGINUI",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011364"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "KD75577",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100200011587"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_1.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_10.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_11.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_12.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_13.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_14.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_15.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_16.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_17.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_18.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_19.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_2.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_20.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_21.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_22.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_23.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_24.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_3.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_4.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_5.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_6.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_7.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_8.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4CORE105_INST_EXPORT_9.zip",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200011254"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_AR.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_BG.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_CA.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_CS.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_DA.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_DE.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_EL.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_EN.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_ES.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_ET.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_FI.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_FR.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_HE.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_HI.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_HR.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_HU.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_IT.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_JA.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_KK.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_KO.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_LT.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_LV.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_MS.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_NL.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_NO.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_PL.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_PT.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_RO.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_RU.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_SH.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_SK.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_SL.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_SV.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_TH.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_TR.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_UK.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_VI.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_ZF.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "S4HANAOP105_ERP_LANG_ZH.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100900003539"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "SAPEXEDB_100-70005282.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000101100053841"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "SAPEXE_100-70005283.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000101100053841"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "SAPHOSTAGENT51_51-20009394.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000101100053919"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "SAP_HR608.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "67837800100200023884"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "SAP_UI755.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100200011342"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "SRA004600.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "67838200100200021264"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "ST-PI740.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "67838200100200024359"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "SUM20SP10_1-80002456.SAR",
            target_dir  = Package.dir_app,
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "UIHR002100.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200006076"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "UIHR002100.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200002606"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        Package(
            name        = "UITRV001300.SAR",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73555000100200008904"},
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),


    ],
)

RTI = Scenario(
    required_params = [],
    packages = [
        Package(
            name        = "SAPCAR",
            target_dir  = Package.dir_rti,
            retr_params = {"ENR": "67838200100200019185"},
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        
    ],
)

HDB = Scenario(
    required_params = [
        "product_version",
    ],
    packages = [
        #  _    _          _   _            __   ___  
        # | |  | |   /\   | \ | |   /\     /_ | / _ \ 
        # | |__| |  /  \  |  \| |  /  \     | || | | |
        # |  __  | / /\ \ | . ` | / /\ \    | || | | |
        # | |  | |/ ____ \| |\  |/ ____ \   | || |_| |
        # |_|  |_/_/    \_\_| \_/_/    \_\  |_(_)___/ 
        #                                             
        #############################################################
        # HANA Platform 1.0
        Package(
            name        = "IMDB_PLATFORM100",
            target_dir  = Package.dir_db,
            retr_params = {"ENR": "01200314690900003484", "SWTYPSC":  "N", "PECCLSC":  "NONE", "V":  "INST", "TA": "ACTUAL"},
            condition   = ['db.product_version == "1.0"', '"PLATFORM" in db.components'],
            filter      = ['"1.0" in r["Description"]', '"SAP HANA Platf" in r["Description"]','"ZIP" in r["Infotype"]'],
            os_avail    = [Package.os_indep],
            os_var      = 'Package.os_indep',
            selector    = Package.selector_newest,
        ),                            
        # HANA Database 1.0 (Linux only)
        Package(
            name        = "IMDB_SERVER100",
            target_dir  = Package.dir_db,
            retr_params = {"ENR": "01200615320200017790"},
            condition   = ['db.product_version == "1.0"', '"DATABASE" in db.components'],
            filter      = ['"Maintenance Revision" in r["Description"]'],
            os_avail    = [Package.os_linux],
            os_var      = 'Package.os_linux',
            selector    = Package.selector_newest,
        ),
        #############################################################
        # HANA Client for HANA 1.0 (Windows/Linux)
        Package(
            name        = "IMDB_CLIENT100",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "01200615320200017866"},
            condition   = ['db.product_version == "1.0"', '"CLIENT" in db.components'],
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        #############################################################
        # HANA Studio for HANA 1.0 (Windows/Linux)
        Package(
            name        = "IMC_STUDIO1",
            target_dir  = Package.dir_db,
            retr_params = {"ENR": "73554900100200000585"},
            condition   = ['db.product_version == "1.0"', '"STUDIO" in db.components'],
            filter      = ['"Revision 1" in r["Description"]'],
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'Config.bastion_os',
            selector    = Package.selector_newest,
        ),
        #  _    _          _   _            ___    ___  
        # | |  | |   /\   | \ | |   /\     |__ \  / _ \ 
        # | |__| |  /  \  |  \| |  /  \       ) || | | |
        # |  __  | / /\ \ | . ` | / /\ \     / / | | | |
        # | |  | |/ ____ \| |\  |/ ____ \   / /_ | |_| |
        # |_|  |_/_/    \_\_| \_/_/    \_\ |____(_)___/ 
        #                                               
        #############################################################
        # HANA Platform 2.0
        Package(
            name        = "IMDB_PLATFORM200",
            target_dir  = Package.dir_db,
            retr_params = {"ENR": "73554900100900001301", "SWTYPSC":  "N", "PECCLSC":  "NONE", "V":  "INST", "TA": "ACTUAL"},
            condition   = ['db.product_version == "2.0"', '"PLATFORM" in db.components'],
            filter      = ['"2.0" in r["Description"]', '"86_64" in r["Description"]','"ZIP" in r["Infotype"]'],
            os_avail    = [Package.os_indep],
            os_var      = 'Package.os_indep',
            selector    = Package.selector_newest,
        ),
        # HANA Database 2.0 (Linux only)
        Package(
            name        = "IMDB_SERVER200",
            target_dir  = Package.dir_db,
            retr_params = {"ENR": "73554900100200005327"},
            condition   = ['db.product_version == "2.0"', '"DATABASE" in db.components'],
            filter      = ['"Revision" in r["Description"]'],
            os_avail    = [Package.os_linux],
            os_var      = 'Package.os_linux',
            selector    = Package.selector_newest,
        ),
        #############################################################
        # HANA Client for HANA 2.0 (Windows/Linux)
        Package(
            name        = "IMDB_CLIENT20-NT_X64",
            target_dir  = Package.dir_app,
            retr_params = {"ENR": "73554900100200005390"},
            condition   = ['db.product_version == "2.0"', '"CLIENT" in db.components'],
            filter      = None,
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'app.os_type',
            selector    = Package.selector_newest,
        ),
        #############################################################
        # HANA Studio for HANA 2.0 (Windows/Linux)
        Package(
            name        = "IMC_STUDIO2-NT_X64",
            target_dir  = Package.dir_db,
            retr_params = {"ENR": "73554900100200000585"},
            condition   = ['db.product_version == "2.0"', '"STUDIO" in db.components'],
            filter      = ['"Revision 2" in r["Description"]'],
            os_avail    = [Package.os_linux, Package.os_windows],
            os_var      = 'Config.bastion_os',
            selector    = Package.selector_newest,
        ),
        # __   __ _____         
        # \ \ / // ____|  /\    
        #  \ V /| (___   /  \   
        #   > <  \___ \ / /\ \  
        #  / . \ ____) / ____ \ 
        # /_/ \_\_____/_/    \_\
        #
        #############################################################
        # XS Advanced Runtime (SAP Extended App Services)
        Package(
            name        = "EXTAPPSER00P",
            target_dir  = Package.dir_db,
            retr_params = {"ENR": "73555000100200004274"},
            condition   = ['"XSA" in db.components'],
            filter      = None,
            os_avail    = [Package.os_linux],
            os_var      = 'Package.os_linux',
            selector    = Package.selector_newest,
        ),
        # DI Core
        Package(
            name        = "XSACDEVXDI",
            target_dir  = Package.dir_db,
            retr_params = {
                "ENR"           : "73554900100200003056",
                "PECCLSC"       : "PLTFRM",
                "INCL_PECCLSC2" : "DB",
                "PECGRSC2"      : "HDB"
            },
            condition   = ['"XSA" in db.components'],
            filter      = None,
            os_avail    = [Package.os_indep],
            os_var      = 'Package.os_indep',
            selector    = Package.selector_newest,
        ),
        # SAPUI5 FESV4
        Package(
            name        = "XSACUI5FESV4",
            target_dir  = Package.dir_db,
            retr_params = {"ENR": "73554900100200006811"},
            condition   = ['"XSA" in db.components'],
            filter      = None,
            os_avail    = [Package.os_indep],
            os_var      = 'Package.os_indep',
            selector    = Package.selector_newest,
        ),
    ]
)

avail_apps  = {"S4": S4}
avail_dbs = {"HANA": HDB}
avail_rtis = {"RTI": RTI}
