---

- name: Ensure variables are available
  include_vars:
    file: "/var/lib/waagent/custom-script/download/0/sapansible/ansible/vars/sap-disks.yml"

- include_tasks: configure.yml
  loop: "{{ sap_swap }}"
  when: item.tier == "all" or item.tier == tier
